#!/usr/bin/env bash
# rite a Bash script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself)

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service nginx restart
sudo service nginx reload
