#!/usr/nin/env bash
# A Bash script that displays the content of the file /etc/passwd.
IFS=":"

while read -r username uid home
do
    echo "$username"
    echo "$uid"
    echo "$home"
done < "/etc/passwd"

