#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# But prints Hi on the 9th line instead of Best School
i=0

while [ $i -lt 10 ]
do
    if ((i == 8))
    then
        echo -e "Best School \n Hi"
    else
        echo "Best School"
    fi
    ((i++))
done