#!/usr/bin/bash
# Write a Bash script that configures an Ubuntu server with the below requirements.

sed -i 's/^127.0.0.1\slocalhost$/127.0.0.2 localhost/' /etc/hosts
sed -i 's/^.*\bfacebook.com$/8.8.8.8 facebook.com/' /etc/hosts

systemctl restart systemd-resolved.service
