#!/usr/bin/env bash
# Write a bash script that displays all active IPv4 IPs on the machine it’s executed on.

ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | grep -Eo "([0-9]*\.){3}[0-9]*" | cut -b 11-